name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deployment script execution
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker image rm -f portfolio &&
            sudo docker build --no-cache ~/dev/portfolio -t portfolio &&
            sudo docker stop portfolio_container &&
            sudo docker run -dit -p 8080:80 --rm --name portfolio_container portfolio
